---
- name: Create PVs for Users
  hosts: nfs
  tasks:
    - name: Create PVs script
      script: ../scripts/create-pvs.sh
      become: true
    - name: Restarting NFS Server...
      shell: systemctl restart nfs-server
      become: true
