apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "tasks", "namespace": "", "kind": "DeploymentConfig"}]'
  labels:
    name: tasks-bc
  name: tasks-bc
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        def APP_NAME = 'tasks'
        def DEV_PROJECT = 'tasks-dev'
        def TEST_PROJECT = 'tasks-test'
        def PROD_PROJECT = 'tasks-prod'
        def BUILD_PROJECT = 'tasks-build'
        pipeline {
          agent {
            node {
              label 'maven'
            }
          }
          options {
            timeout(time: 20, unit: 'MINUTES')
          }
          stages {
            stage('Build') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject(BUILD_PROJECT) {
                      def buildConfig = openshift.selector('bc', APP_NAME)
                      def build = buildConfig.startBuild()
                      build.logs('-f')
                    }
                  }
                }
              }
            }
            stage('Deploy to build env') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject(BUILD_PROJECT) {
                      def deploymentConfig = openshift.selector('dc', APP_NAME)
                      deploymentConfig.deploy()
                    }
                  }
                }
              }
            }
            stage ('Verify build env') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject(BUILD_PROJECT) {
                      def latestDeploymentVersion = openshift.selector('dc', "${APP_NAME}").object().status.latestVersion
                      def rc = openshift.selector('rc', "${APP_NAME}-${latestDeploymentVersion}")
                      rc.untilEach(1){
                        def rcMap = it.object()
                        return (rcMap.status.replicas.equals(rcMap.status.readyReplicas))
                      }
                    }
                  }
                }
              }
            }
            stage ('Promote to dev env') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject(DEV_PROJECT) {
                      openshift.tag("${BUILD_PROJECT}/${APP_NAME}:latest", "${DEV_PROJECT}/${APP_NAME}:latest")
                      if (!openshift.selector('dc', APP_NAME).exists()) {
                        openshift.newApp(APP_NAME)
                        def svc = openshift.selector('svc', APP_NAME)
                        svc.expose()
                      }
                    }
                  }
                }
              }
            }
            stage ('Verify dev env') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject(DEV_PROJECT) {
                      def latestDeploymentVersion = openshift.selector('dc', "${APP_NAME}").object().status.latestVersion
                      def rc = openshift.selector('rc', "${APP_NAME}-${latestDeploymentVersion}")
                      rc.untilEach(1){
                        def rcMap = it.object()
                        return (rcMap.status.replicas.equals(rcMap.status.readyReplicas))
                      }
                    }
                  }
                }
              }
            }
            stage ('Promote to test env') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject(TEST_PROJECT) {
                      openshift.tag("${DEV_PROJECT}/${APP_NAME}:latest", "${TEST_PROJECT}/${APP_NAME}:latest")
                      if (!openshift.selector('dc', APP_NAME).exists()) {
                        openshift.newApp(APP_NAME)
                        def svc = openshift.selector('svc', APP_NAME)
                        svc.expose()
                      }
                    }
                  }
                }
              }
            }
            stage ('Verify test env') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject(TEST_PROJECT) {
                      def latestDeploymentVersion = openshift.selector('dc', "${APP_NAME}").object().status.latestVersion
                      def rc = openshift.selector('rc', "${APP_NAME}-${latestDeploymentVersion}")
                      rc.untilEach(1){
                        def rcMap = it.object()
                        return (rcMap.status.replicas.equals(rcMap.status.readyReplicas))
                      }
                    }
                  }
                }
              }
            }
            stage ('Promote to prod env') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject(PROD_PROJECT) {
                      openshift.tag("${TEST_PROJECT}/${APP_NAME}:latest", "${PROD_PROJECT}/${APP_NAME}:latest")
                      if (!openshift.selector('dc', APP_NAME).exists()) {
                        openshift.newApp(APP_NAME)
                        def svc = openshift.selector('svc', APP_NAME)
                        svc.expose()
                      }
                    }
                  }
                }
              }
            }
            stage ('Verify prod env') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject(PROD_PROJECT) {
                      def latestDeploymentVersion = openshift.selector('dc', "${APP_NAME}").object().status.latestVersion
                      def rc = openshift.selector('rc', "${APP_NAME}-${latestDeploymentVersion}")
                      rc.untilEach(1){
                        def rcMap = it.object()
                        return (rcMap.status.replicas.equals(rcMap.status.readyReplicas))
                      }
                    }
                  }
                }
              }
            }
          }
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: CzgPZAZ5m2
    type: GitHub
  - generic:
      secret: CzgPZAZ5m2
type: Generic
